---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

'Twas brillig, and the slithy toves  
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
And the mome raths outgrabe.  
'Beware the Jabberwock, my son!  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Some say the world will end in fire,  
Some say in ice.  
From what I've tasted of desire  
I hold with those who favor fire.  
But if it had to perish twice,  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,  
Shining with all his might:  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

I come with no wrapping or pretty pink bows.   
 I am who I am from my head to my toes.  
 I tend to get loud when speaking my mind.   
 Even a little crazy some of the time.   
 I'm not a size 5 and don't care to be.   
 You can be you and I can be me.   
 I try to stay strong when pain knocks me down.   
 And the times that I cry is when no one's around.   
 To error is human or so that's what they say.   
 Well, tell me who's perfect anyway  
